#!/usr/bin/env npx tsx
import fs from 'fs';import os from 'os';import path from 'path';import { randomUUID } from 'crypto';
const DEFAULT_DB_PATH=path.join(os.homedir(),'.openclaw/memory/lancedb');const DEFAULT_CONFIG_PATH=path.join(os.homedir(),'.openclaw/openclaw.json');const DEFAULT_SESSIONS_GLOB=path.join(os.homedir(),'.openclaw/agents/main/sessions');
function loadKey(cfg:string){const j=JSON.parse(fs.readFileSync(cfg,'utf8'));const k=j?.plugins?.entries?.['memory-lancedb']?.config?.embedding?.apiKey;if(!k)throw new Error('OpenAI API key not found in openclaw.json at plugins.entries.memory-lancedb.config.embedding.apiKey');return k;}
async function post(url:string,p:any,key:string){const r=await fetch(url,{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify(p)});if(!r.ok) throw new Error(await r.text());return r.json();}
async function embed(api:string,texts:string[]){if(!texts.length)return [];const d:any=await post('https://api.openai.com/v1/embeddings',{model:'text-embedding-3-small',input:texts},api);return d.data.map((x:any)=>x.embedding as number[])}
async function extract(api:string,transcript:string){const p={model:'gpt-4o-mini',temperature:0,response_format:{type:'json_object'},messages:[{role:'system',content:'You extract long-term memory facts from assistant-user conversation transcripts. Output only strict JSON with schema: {"facts": ["..."]}. Rules: ignore casual chatter; include only durable, useful facts/preferences/decisions/entities. Resolve pronouns to explicit nouns/names whenever possible using transcript context. Each fact must be atomic and self-contained. No duplicates, no meta-commentary.'},{role:'user',content:transcript}]};const out:any=await post('https://api.openai.com/v1/chat/completions',p,api);const parsed=JSON.parse(out.choices?.[0]?.message?.content||'{"facts":[]}');const seen=new Set<string>();const cleaned:string[]=[];for(const f of parsed.facts||[]){if(typeof f!=='string')continue;const s=f.replace(/\s+/g,' ').trim();if(!s)continue;const k=s.toLowerCase();if(seen.has(k))continue;seen.add(k);cleaned.push(s);}return cleaned;}
function filesSince(dir:string,since:number){return fs.readdirSync(dir).filter(n=>n.endsWith('.jsonl')&&!n.includes('.deleted.')).map(n=>path.join(dir,n)).filter(p=>fs.statSync(p).mtimeMs>=since).sort();}
function transcript(p:string,since:number){const out:string[]=[];for(const raw of fs.readFileSync(p,'utf8').split(/\r?\n/)){if(!raw.trim())continue;let o:any;try{o=JSON.parse(raw);}catch{continue;}if(o.type!=='message')continue;const m=o.message||{};const role=m.role; if(!['user','assistant'].includes(role))continue;const ts=Date.parse((o.timestamp||m.timestamp||'').replace('Z','+00:00'));if(Number.isFinite(ts)&&ts<since)continue;const t=(m.content||[]).filter((x:any)=>x?.type==='text'&&typeof x.text==='string').map((x:any)=>x.text).join('\n').trim();if(t)out.push(`${String(role).toUpperCase()}: ${t}`);}let j=out.join('\n');if(j.length>24000)j=j.slice(-24000);return j;}
async function main(){const argv=process.argv.slice(2);const sinceHours=Number(argv[argv.indexOf('--since-hours')+1]||24);const sessionsDir=(argv[argv.indexOf('--sessions-glob')+1]||DEFAULT_SESSIONS_GLOB).replace(/\*\.jsonl$/,'');const dbPath=argv[argv.indexOf('--db-path')+1]||DEFAULT_DB_PATH;const cfg=argv[argv.indexOf('--config')+1]||DEFAULT_CONFIG_PATH;const since=Date.now()-sinceHours*3600_000;const api=loadKey(cfg);const files=filesSince(sessionsDir,since);
const facts:string[]=[];for(const f of files){const t=transcript(f,since);if(!t.trim())continue;facts.push(...await extract(api,t));}
const dedup=[...new Map(facts.map(f=>[f.toLowerCase(),f])).values()];let vectors:number[][]=[];let table:any=null;if(dedup.length){vectors=await embed(api,dedup);const l:any=(await import('lancedb')).default ?? await import('lancedb');const db=await l.connect(dbPath);const names=new Set(await db.tableNames());if(names.has('memories')) table=await db.openTable('memories'); else {table=await db.createTable('memories',[{id:'__schema__',text:'',vector:Array(vectors[0].length).fill(0),importance:0,category:'fact',createdAt:0,source:'session_extract'}]);await table.delete('id = "__schema__"');}}
let stored=0,dupes=0;for(let i=0;i<dedup.length;i++){const vec=vectors[i];let rows:any[]=[];try{rows=await table.search(vec).limit(8).toArray();}catch{try{rows=await table.vectorSearch(vec).limit(8).toArray();}catch{rows=[];}}const isDup=rows.some(r=>1/(1+Number(r._distance||0))>0.95);if(isDup){dupes++;continue;}await table.add([{id:randomUUID(),text:dedup[i],vector:vec,importance:0.8,category:'fact',createdAt:Date.now(),source:'session_extract'}]);stored++;}
console.log(`Processed ${files.length} sessions, extracted ${dedup.length} facts, stored ${stored} new memories (${dupes} duplicates skipped)`);
}
main().catch(e=>{console.error(e instanceof Error?e.message:String(e));process.exit(1)});
