#!/usr/bin/env npx tsx
import fs from 'fs';import path from 'path';import { spawnSync } from 'child_process';import { resolveRepoPath } from '../lib/paths.js';import { runPsql } from '../lib/db.js';
const WORKSPACE=resolveRepoPath();const PROMPT_FILE=path.join(WORKSPACE,'tools/memory/prompts/fact_extraction.txt');const SESS=path.join(process.env.HOME||'','.openclaw/agents/main/sessions');
const q=(v:any)=>v==null?'NULL':`'${String(v).replace(/'/g,"''")}'`;const psql=(s:string,c=false)=>{const p=runPsql(s,{args:['-q','-v','ON_ERROR_STOP=1','-A','-t','-X']});if(p.status!==0)throw new Error((p.stderr||'psql failed').trim());return c?(p.stdout||'').trim():''};
const embed=(text:string)=>{const bin=path.join(WORKSPACE,'tools/embeddings/embed');const script=path.join(WORKSPACE,'tools/embeddings/embed.py');const p=spawnSync(fs.existsSync(bin)?bin:'python3',fs.existsSync(bin)?['embed','--text',text]:[script,'embed','--text',text],{encoding:'utf8'});if(p.status!==0)throw new Error((p.stderr||p.stdout||'embedding failed').trim());const j=JSON.parse(p.stdout||'{}');if(!j.vectors?.[0])throw new Error('no embedding returned');return j.vectors[0].map((x:any)=>Number(x));};
const vec=(v:number[])=>`'[${v.map(x=>x.toFixed(8)).join(',')}]'::vector`;
const call=async(prompt:string,model:string)=>{const payload={model,prompt,stream:false,format:'json',options:{temperature:0.1}};const p=spawnSync('curl',['-sS','http://127.0.0.1:11434/api/generate','-d',JSON.stringify(payload)],{encoding:'utf8',timeout:180000});if(p.status!==0)throw new Error((p.stderr||'ollama call failed').trim());const wrap=JSON.parse(p.stdout||'{}');const r=(wrap.response||'{}').trim();try{return JSON.parse(r)}catch{const i=r.indexOf('{'),j=r.lastIndexOf('}');if(i>=0&&j>i)try{return JSON.parse(r.slice(i,j+1))}catch{};return {facts:[]}}};
function normalize(raw:any){try{const fact_type=String(raw.type||'').trim();const content=String(raw.content||'').replace(/\s+/g,' ').trim();if(!['fact','preference','event','system_rule'].includes(fact_type)||content.length<8)return null;return {fact_type,content,tags:(raw.tags||[]).map(String).filter(Boolean).slice(0,12),people:(raw.people||[]).map(String).filter(Boolean).slice(0,12),projects:(raw.projects||[]).map(String).filter(Boolean).slice(0,12),importance:Math.max(0,Math.min(1,Number(raw.importance||0.5))),confidence:Math.max(0,Math.min(1,Number(raw.confidence||0.5))),supersedes_id:raw.supersedes_id?Number(raw.supersedes_id):null};}catch{return null}}
function neighbors(v:number[]){const rows=psql(`SELECT id, object_value, 1 - (embedding_local <=> ${vec(v)}) AS similarity FROM cortana_memory_semantic WHERE active=TRUE AND embedding_local IS NOT NULL AND (1 - (embedding_local <=> ${vec(v)})) >= 0.85 ORDER BY embedding_local <=> ${vec(v)} LIMIT 5;`,true).split(/\r?\n/).filter(Boolean);return rows.map(r=>{const [id,text,sim]=r.split('|',3);return [Number(id),text,Number(sim)] as const});}
async function classify(a:string,b:string,model:string){try{const p=await call(`Return only JSON {"identical":true|false,"updated":true|false}. identical=true when both statements mean the same thing. updated=true when B should supersede A (same subject, newer/corrected detail).\nA: ${a}\nB: ${b}\n`,model);return [!!p.identical,!!p.updated] as const;}catch{return [false,false] as const}}
function insert(f:any,source:string,v:number[],sup:number|null,dry:boolean){if(dry)return {action:'would_insert',fact:f.content,supersedes_id:sup};const md=JSON.stringify({atomic_fact:true,importance:f.importance,tags:f.tags,people:f.people,projects:f.projects});const id=Number(psql(`INSERT INTO cortana_memory_semantic (fact_type, subject, predicate, object_value, confidence, trust, stability, first_seen_at, last_seen_at, source_type, source_ref, fingerprint, metadata, embedding_local, embedding_model, extraction_source, supersedes_id) VALUES (${q(f.fact_type)}, 'hamel','stated',${q(f.content)},${f.confidence.toFixed(3)},${Math.max(0.5,f.confidence).toFixed(3)},${Math.max(0.4,f.importance).toFixed(3)},NOW(),NOW(),'atomic_extraction',${q(source)},md5(${q(`${f.fact_type}|${f.content}`)}),${q(md)}::jsonb,${vec(v)},'BAAI/bge-small-en-v1.5',${q(source)},${sup??'NULL'}) ON CONFLICT (fact_type, subject, predicate, object_value) DO UPDATE SET last_seen_at=NOW(), confidence=GREATEST(cortana_memory_semantic.confidence,EXCLUDED.confidence), metadata=cortana_memory_semantic.metadata||EXCLUDED.metadata RETURNING id;`,true)); if(sup) psql(`UPDATE cortana_memory_semantic SET active=FALSE, superseded_by=${id}, superseded_at=NOW() WHERE id=${sup};`); return {action:'insert',id,fact:f.content,supersedes_id:sup};}
function transcript(p:string){const lines:string[]=[];for(const raw of fs.readFileSync(p,'utf8').split(/\r?\n/)){if(!raw.trim())continue;let o:any;try{o=JSON.parse(raw)}catch{continue;}if(o.type!=='message')continue;const m=o.message||{};if(!['user','assistant'].includes(m.role))continue;const t=(m.content||[]).filter((c:any)=>c?.type==='text'&&typeof c.text==='string').map((c:any)=>c.text).join(' ').trim();if(t)lines.push(`${m.role.toUpperCase()}: ${t}`);}return lines.join('\n');}
async function processText(text:string,source:string,model:string,dry:boolean){const tmpl=fs.readFileSync(PROMPT_FILE,'utf8');const prompt=tmpl.replace('{{TRANSCRIPT}}',text.slice(0,18000)).replace('{{EXISTING_FACTS}}','[]');const parsed:any=await call(prompt,model);const out:any[]=[];for(const item of parsed.facts||[]){const f=normalize(item);if(!f)continue;const v=embed(f.content);const n=neighbors(v)[0];if(n){const [ident,upd]=await classify(n[1],f.content,model);if(ident){out.push({action:'skip_duplicate',existing_id:n[0],similarity:Number(n[2].toFixed(4)),fact:f.content});continue;}if(upd){out.push(insert(f,source,v,n[0],dry));continue;}}out.push(insert(f,source,v,null,dry));}return out;}
async function main(){const a=process.argv.slice(2);const cmd=a[0];const model=a[a.indexOf('--model')+1]||'phi3:mini';const dry=a.includes('--dry-run');psql(`ALTER TABLE cortana_memory_semantic ADD COLUMN IF NOT EXISTS extraction_source TEXT, ADD COLUMN IF NOT EXISTS embedding_local VECTOR(384), ADD COLUMN IF NOT EXISTS superseded_by BIGINT, ADD COLUMN IF NOT EXISTS superseded_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS supersedes_id BIGINT;`);
if(cmd==='extract'){const input=a[a.indexOf('--input')+1];if(!input){console.error('missing --input');process.exit(2);}const text=input==='-'?fs.readFileSync(0,'utf8'):(input.endsWith('.jsonl')?transcript(input):fs.readFileSync(input,'utf8'));const results=await processText(text,input==='-'?'stdin':input,model,dry);console.log(JSON.stringify({ok:true,mode:'extract',source:input==='-'?'stdin':input,count:results.length,results},null,2));return;}
if(cmd==='batch'){const h=Number(a[a.indexOf('--since-hours')+1]||24);const cutoff=Date.now()-h*3600_000;const files=fs.readdirSync(SESS).filter(f=>f.endsWith('.jsonl')&&!f.includes('.deleted.')).map(f=>path.join(SESS,f)).filter(f=>fs.statSync(f).mtimeMs>=cutoff).sort();const all:any[]=[];for(const f of files){const t=transcript(f);if(t.trim())all.push(...await processText(t,f,model,dry));}console.log(JSON.stringify({ok:true,mode:'batch',since_hours:h,sessions:files.length,result_count:all.length,results:all},null,2));return;}
console.error('usage: extract_facts.ts {extract|batch} ...');process.exit(2)}
main().catch(e=>{console.error(e instanceof Error?e.message:String(e));process.exit(1)});
