#!/usr/bin/env npx tsx
import fs from 'fs';import { runPsql } from '../lib/db.js';
const ACTION=new Set(['must','should','need','todo','remember','prefer','rule','plan','schedule','review','fix','send','build']);const LONG=['always','never','preference','policy','rule','habit','routine','goal','weekly','monthly','career','health','finance'];const SHORT=['today','tomorrow','asap','immediately','now','temporary','one-time'];const NEG=[' not ',' never ',' no ',' don\'t ',' do not ',' avoid ',' stop '];
const toks=(t:string)=>new Set((t.toLowerCase().match(/[A-Za-z][A-Za-z0-9_'-]{2,}/g)||[]));const sim=(a:string,b:string)=>{const ta=toks(a),tb=toks(b);const inter=[...ta].filter(x=>tb.has(x)).length;const jac=(ta.size||tb.size)?inter/(ta.size+tb.size-inter):0;return Math.max(jac, a.toLowerCase()===b.toLowerCase()?1:0)};
function q(sql:string){const p=runPsql(sql,{args:['-q','-X','-v','ON_ERROR_STOP=1','-t','-A']});if(p.status!==0) throw new Error((p.stderr||'psql failed').trim());return (p.stdout||'').trim();}
function fetch(sql:string){try{return JSON.parse(q(`SELECT COALESCE(json_agg(t),'[]'::json)::text FROM (${sql}) t;`)||'[]')}catch{return[]}}
function corpus(limit:number){return fetch(`WITH e AS (SELECT 'episodic' tier,id::text id,COALESCE(happened_at::text,NOW()::text) ts,TRIM(COALESCE(summary,'')||' '||COALESCE(details,'')) body FROM cortana_memory_episodic WHERE active=TRUE ORDER BY happened_at DESC NULLS LAST LIMIT ${limit}), s AS (SELECT 'semantic' tier,id::text id,COALESCE(last_seen_at::text,first_seen_at::text,NOW()::text) ts,TRIM(COALESCE(subject,'')||' '||COALESCE(predicate,'')||' '||COALESCE(object_value,'')) body FROM cortana_memory_semantic WHERE active=TRUE ORDER BY last_seen_at DESC NULLS LAST LIMIT ${limit}), p AS (SELECT 'procedural' tier,id::text id,COALESCE(updated_at::text,created_at::text,NOW()::text) ts,TRIM(COALESCE(workflow_name,'')||' '||COALESCE(trigger_context,'')||' '||COALESCE(expected_outcome,'')) body FROM cortana_memory_procedural WHERE deprecated=FALSE ORDER BY updated_at DESC NULLS LAST LIMIT ${limit}) SELECT * FROM (SELECT * FROM e UNION ALL SELECT * FROM s UNION ALL SELECT * FROM p) x WHERE COALESCE(body,'')<>'' ORDER BY ts DESC LIMIT ${limit*2}`)}
function evaluate(text:string,limit:number){const mem=corpus(limit);const scored=mem.map((r:any)=>[sim(text,String(r.body||'')),r] as const).filter(([s])=>s>=0.35).sort((a,b)=>b[0]-a[0]);const top=scored.slice(0,8);const rec=scored.filter(([s])=>s>=0.72).length;const novelty=Math.max(0,1-(top[0]?.[0]||0));const tt=` ${text.toLowerCase()} `;const action=Math.min(1,0.25+[...ACTION].filter(w=>tt.includes(` ${w} `)).length*0.12 +(/\b(do|build|send|review|fix|create|schedule|call|ship|track|improve)\b/.test(tt)?0.15:0)+(/\b(today|tomorrow|week|month|by\s+\w+day|\d{1,2}:\d{2})\b/.test(tt)?0.15:0));const l=LONG.filter(w=>tt.includes(w)).length,s=SHORT.filter(w=>tt.includes(w)).length;const shelf=l===0&&s===0?0.55:Math.max(0,Math.min(1,0.5+0.1*l-0.12*s));const recurrence=Math.max(0,1-Math.min(rec,8)/8);const weighted=novelty*0.35+action*0.25+recurrence*0.2+shelf*0.2;const verdict=weighted>=0.68&&novelty>=0.4?'promote':weighted>=0.45?'hold':'archive';const supers=top.flatMap(([s,r]:any)=>{const ov=[...toks(text)].filter(x=>toks(String(r.body||'')).has(x));const n=NEG.some(w=>` ${text.toLowerCase()} `.includes(w));const o=NEG.some(w=>` ${String(r.body||'').toLowerCase()} `.includes(w));return ov.length>=3&&n!==o?[{tier:r.tier,id:r.id,similarity:Number(s.toFixed(3)),demote_recommended:true,reason:'polarity flip with shared anchors',new_memory_timestamp:new Date().toISOString()}]:[]});return {verdict,scores:{novelty:Number(novelty.toFixed(3)),actionability:Number(action.toFixed(3)),recurrence:Number(recurrence.toFixed(3)),shelf_life:Number(shelf.toFixed(3)),weighted:Number(weighted.toFixed(3))},recurrence_count:rec,matched_examples:top.map(([s,r]:any)=>({tier:r.tier,id:r.id,similarity:Number(s.toFixed(3)),text_preview:String(r.body||'').slice(0,180)})),supersession_flags:supers,reasons:[novelty<0.35?'low novelty':'',action<0.35?'low actionability':'',shelf<0.35?'short shelf-life':''].filter(Boolean)}}
async function main(){const a=process.argv.slice(2);let text='';const ti=a.indexOf('--text'),tf=a.indexOf('--text-file');if(ti>=0)text=a[ti+1]||'';if(tf>=0)text=fs.readFileSync(a[tf+1],'utf8').trim();if(!text){console.error('Provide --text or --text-file');process.exit(1);}const res=evaluate(text,Number(a[a.indexOf('--corpus-limit')+1]||300));if(a.includes('--log-event')&&!a.includes('--dry-run')){const payload=JSON.stringify({memory_text:text.slice(0,500),source_type:a[a.indexOf('--source-type')+1]||'manual',source_ref:a[a.indexOf('--source-ref')+1],result:res}).replace(/'/g,"''");q(`INSERT INTO cortana_events (event_type,source,severity,message,metadata) VALUES ('memory_quality_gate','memory_quality_gate.py','info','Evaluated memory candidate: ${res.verdict}','${payload}'::jsonb);`);}console.log(JSON.stringify(res,null,2));}
main().catch(e=>{console.error(e instanceof Error?e.message:String(e));process.exit(1)});
