#!/usr/bin/env npx tsx
import fs from 'fs';import path from 'path';import { resolveRepoPath } from '../lib/paths.js';import { readJsonFile, writeJsonFileAtomic } from '../lib/json-file.js';import { spawnSync } from 'child_process';
const WORKSPACE=resolveRepoPath();const STATE_PATH=path.join(WORKSPACE,'memory/vector-memory-health-state.json');
const state=()=>readJsonFile<any>(STATE_PATH)||{};const save=(s:any)=>writeJsonFileAtomic(STATE_PATH,s,2);
function parse(raw:string){raw=raw.trim();if(!raw)return null;const i=Math.min(...['[','{'].map(c=>{const x=raw.indexOf(c);return x<0?1e9:x}));if(i<1e9)raw=raw.slice(i);try{return JSON.parse(raw)}catch{return null}}
function vector(query:string,max:number){const p=spawnSync('openclaw',['memory','search',query,'--json','--max-results',String(max)],{encoding:'utf8',timeout:90000});const combined=`${p.stdout}\n${p.stderr}`.trim();const payload=parse(p.stdout||'');let items:any[]=[];if(Array.isArray(payload))items=payload.filter(x=>x&&typeof x==='object');else if(payload&&typeof payload==='object') for(const k of ['results','items','matches','data']) if(Array.isArray((payload as any)[k])){items=(payload as any)[k].filter((x:any)=>x&&typeof x==='object');break;}const tl=combined.toLowerCase();const quota=/(resource_exhausted|embedd\w*[^\n]{0,80}429|429[^\n]{0,80}embedd\w*)/.test(tl)&&/(failed|error|quota)/.test(tl);if(p.status!==0||quota)return [null,combined] as const;return [items,combined] as const;}
function collect(){const out:string[]=[];const r=path.join(WORKSPACE,'MEMORY.md');if(fs.existsSync(r))out.push(r);const m=path.join(WORKSPACE,'memory');if(fs.existsSync(m)) for(const f of fs.readdirSync(m).filter(f=>f.endsWith('.md')).sort()) out.push(path.join(m,f));return out;}
function fallback(query:string,max:number){const terms=(query.toLowerCase().match(/[a-zA-Z0-9_]+/g)||[]).filter(t=>t.length>=3);if(!terms.length)terms.push(query.toLowerCase());const hits:any[]=[];for(const p of collect()){const lines=fs.readFileSync(p,'utf8').split(/\r?\n/);const rel=path.relative(WORKSPACE,p);for(let i=0;i<lines.length;i++){const line=lines[i].toLowerCase();let score=0;for(const t of terms)if(line.includes(t))score+=2;if(terms.length>=2&&line.includes(terms[0])&&line.includes(terms[1]))score+=1;if(score>0)hits.push({source:rel,line:i+1,snippet:(lines[i].trim().slice(0,420)),score:Number(score),mode:'keyword_fallback'});}}hits.sort((a,b)=>b.score-a.score);return hits.slice(0,max);}
async function main(){const a=process.argv.slice(2);const query=a.find(x=>!x.startsWith('-'))||'';if(!query){console.error('usage: safe-memory-search.ts QUERY [--max-results N] [--json]');process.exit(2);}const max=Number(a[a.indexOf('--max-results')+1]||5);const asJson=a.includes('--json');const s=state();let mode='vector',errorText='',items:any[]=[];if(!s.fallback_mode){const [v,e]=vector(query,max);errorText=e;if(v!==null)items=v;else{mode='keyword_fallback';items=fallback(query,max);}}else{mode='keyword_fallback';items=fallback(query,max);}if(mode==='keyword_fallback'){s.fallback_mode=true;s.last_fallback_reason=(errorText||'').slice(0,500);save(s);}const out={mode,query,results:items};console.log(JSON.stringify(out,null,asJson?0:2));}
main();
