#!/usr/bin/env npx tsx
import { runPsql } from '../lib/db.js';
const run=(sql:string)=>{const p=runPsql(sql,{args:['-q','-X','-v','ON_ERROR_STOP=1','-t','-A']});if(p.status!==0)throw new Error((p.stderr||p.stdout||'psql failed').trim());return (p.stdout||'').trim();};
const parse=(s:string)=>{try{return JSON.parse(s||'[]')}catch{return[]}};
function ensure(){run(`ALTER TABLE cortana_memory_semantic ADD COLUMN IF NOT EXISTS supersedes_id BIGINT;ALTER TABLE cortana_memory_semantic ADD COLUMN IF NOT EXISTS superseded_by BIGINT;ALTER TABLE cortana_memory_semantic ADD COLUMN IF NOT EXISTS superseded_at TIMESTAMPTZ;UPDATE cortana_memory_semantic older SET superseded_by=newer.id,superseded_at=COALESCE(older.superseded_at,NOW()) FROM cortana_memory_semantic newer WHERE newer.supersedes_id=older.id AND (older.superseded_by IS NULL OR older.superseded_by!=newer.id);CREATE INDEX IF NOT EXISTS idx_memory_semantic_supersedes_id ON cortana_memory_semantic(supersedes_id);CREATE INDEX IF NOT EXISTS idx_memory_semantic_superseded_by ON cortana_memory_semantic(superseded_by);`);}
function chain(id:number){return parse(run(`WITH RECURSIVE walk AS (SELECT id,supersedes_id,superseded_by,0::int AS depth_back FROM cortana_memory_semantic WHERE id=${id} UNION ALL SELECT p.id,p.supersedes_id,p.superseded_by,walk.depth_back+1 FROM cortana_memory_semantic p JOIN walk ON walk.supersedes_id=p.id), oldest AS (SELECT id FROM walk ORDER BY depth_back DESC LIMIT 1), chain AS (SELECT s.id,s.supersedes_id,s.superseded_by,s.superseded_at,s.active,s.fact_type,s.subject,s.predicate,s.object_value,s.first_seen_at,s.last_seen_at,0::int AS depth FROM cortana_memory_semantic s JOIN oldest o ON o.id=s.id UNION ALL SELECT n.id,n.supersedes_id,n.superseded_by,n.superseded_at,n.active,n.fact_type,n.subject,n.predicate,n.object_value,n.first_seen_at,n.last_seen_at,chain.depth+1 FROM cortana_memory_semantic n JOIN chain ON n.supersedes_id=chain.id) SELECT COALESCE(json_agg(row_to_json(t) ORDER BY t.depth ASC),'[]'::json)::text FROM chain t;`));}
function prune(maxDepth:number,dry:boolean){const v=parse(run(`WITH RECURSIVE heads AS (SELECT id AS head_id,id,0::int AS depth_from_head FROM cortana_memory_semantic WHERE superseded_by IS NULL), chain AS (SELECT * FROM heads UNION ALL SELECT chain.head_id,prev.id,chain.depth_from_head+1 FROM chain JOIN cortana_memory_semantic cur ON cur.id=chain.id JOIN cortana_memory_semantic prev ON prev.id=cur.supersedes_id), victims AS (SELECT c.id,c.head_id,c.depth_from_head FROM chain c JOIN cortana_memory_semantic s ON s.id=c.id WHERE c.depth_from_head>${Math.max(0,maxDepth)} AND (s.superseded_by IS NOT NULL OR s.superseded_at IS NOT NULL)) SELECT COALESCE(json_agg(row_to_json(v) ORDER BY v.head_id,v.depth_from_head,v.id),'[]'::json)::text FROM victims v;`));const ids=[...new Set(v.map((x:any)=>Number(x.id)).filter(Boolean))].sort((a,b)=>a-b);if(ids.length&&!dry)run(`UPDATE cortana_memory_semantic SET active=FALSE, metadata=COALESCE(metadata,'{}'::jsonb)||jsonb_build_object('supersession_pruned_at',NOW()::text,'supersession_prune_max_depth',${Math.max(0,maxDepth)}) WHERE id = ANY('{${ids.join(',')}}'::bigint[]);`);return {max_depth:Math.max(0,maxDepth),dry_run:dry,pruned:dry?0:ids.length,candidates:ids.length,ids};}
async function main(){const [cmd,...rest]=process.argv.slice(2);ensure();if(cmd==='chain'){const id=Number(rest[0]);console.log(JSON.stringify({memory_id:id,chain:chain(id)},null,2));return;}if(cmd==='prune'){const md=Number(rest[rest.indexOf('--max-depth')+1]||3);const dry=rest.includes('--dry-run');console.log(JSON.stringify(prune(md,dry),null,2));return;}console.error('usage: supersession.ts chain <memory_id> | prune [--max-depth N] [--dry-run]');process.exit(2)}
main().catch(e=>{console.error(e instanceof Error?e.message:String(e));process.exit(1)});
