#!/usr/bin/env npx tsx
import path from 'path';import { spawnSync } from 'child_process';import { resolveRepoPath } from '../lib/paths.js';import { readJsonFile, writeJsonFileAtomic } from '../lib/json-file.js';import { runPsql } from '../lib/db.js';
const WORKSPACE=resolveRepoPath();const STATE_PATH=path.join(WORKSPACE,'memory/vector-memory-health-state.json');const now=()=>new Date().toISOString();
const run=(cmd:string,args:string[],timeout=120000)=>spawnSync(cmd,args,{encoding:'utf8',timeout});const parse=(r:string)=>{r=r.trim();if(!r)return null;const i=Math.min(...['[','{'].map(c=>{const x=r.indexOf(c);return x<0?1e9:x}));if(i<1e9)r=r.slice(i);try{return JSON.parse(r)}catch{return null}};
const is429=(t:string)=>{t=t.toLowerCase();return /(resource_exhausted|embedd\w*[^\n]{0,80}429|429[^\n]{0,80}embedd\w*)/.test(t)&&/(failed|error|quota)/.test(t)};
function sql(s:string){const p=runPsql(s,{args:['-q','-X','-v','ON_ERROR_STOP=1']});}
function insertIncident(type:string,severity:string,desc:string,tier:number,metadata:any){const sig=type.replace(/'/g,"''");const chk=run('/opt/homebrew/opt/postgresql@17/bin/psql',['cortana','-q','-X','-t','-A','-c',`SELECT COUNT(*) FROM cortana_immune_incidents WHERE status='open' AND threat_signature='${sig}';`]);if(chk.status===0&&Number((chk.stdout||'').trim())>0)return;const meta=JSON.stringify(metadata).replace(/'/g,"''");run('/opt/homebrew/opt/postgresql@17/bin/psql',['cortana','-q','-X','-c',`INSERT INTO cortana_immune_incidents (detected_at, threat_type, source, severity, description, threat_signature, tier, status, playbook_used, auto_resolved, metadata) VALUES (NOW(), '${sig}', 'vector_memory_health', '${severity}', '${desc.replace(/'/g,"''")}', '${sig}', ${tier}, 'open', 'vector_memory_guard', FALSE, '${meta}'::jsonb);`]);}
async function main(){const a=process.argv.slice(2);const asJson=a.includes('--json');const st=readJsonFile<any>(STATE_PATH)||{consecutive_embedding_429:0,fallback_mode:false,reindex_queued:false};const ms=run('openclaw',['memory','status','--json']);const payload:any=parse(ms.stdout||'');const status=Array.isArray(payload)&&payload[0]?.status?payload[0].status:{};const files=Number(status.files||0),chunks=Number(status.chunks||0);
const probe=run('openclaw',['memory','search','vector health probe','--json','--max-results','1'],90000);const combined=`${probe.stdout}\n${probe.stderr}`;const saw429=is429(combined);st.consecutive_embedding_429=saw429?Number(st.consecutive_embedding_429||0)+1:0;
if(chunks===0){st.fallback_mode=true;st.reindex_queued=true;st.queued_at=st.queued_at||now();insertIncident('vector_index_empty','critical','Vector memory index has zero chunks; semantic retrieval unavailable.',1,{files,chunks,provider:status.provider,model:status.model});}
if(Number(st.consecutive_embedding_429)>=3){st.fallback_mode=true;st.reindex_queued=true;st.queued_at=st.queued_at||now();insertIncident('embedding_quota_429','critical','Embedding provider returned 429 three+ consecutive probes; switched to keyword fallback.',1,{consecutive_429:st.consecutive_embedding_429,probe_excerpt:combined.slice(0,500),provider:status.provider,model:status.model});}
let reindex_attempted=false,reindex_ok=false;if(st.reindex_queued&&!saw429){reindex_attempted=true;const re=run('openclaw',['memory','index','--force'],1800000);const out=`${re.stdout}\n${re.stderr}`;reindex_ok=re.status===0&&!is429(out);if(reindex_ok){st.reindex_queued=false;st.fallback_mode=false;st.consecutive_embedding_429=0;st.last_reindex_ok_at=now();delete st.queued_at;} else st.last_reindex_error=out.slice(0,600);}
if(chunks>0&&Number(st.consecutive_embedding_429)===0&&!st.reindex_queued)st.fallback_mode=false;st.last_checked_at=now();st.last_status={files,chunks,provider:status.provider,model:status.model};writeJsonFileAtomic(STATE_PATH,st,2);
const out={ok:chunks>0,files,chunks,consecutive_embedding_429:st.consecutive_embedding_429||0,fallback_mode:!!st.fallback_mode,reindex_queued:!!st.reindex_queued,reindex_attempted,reindex_ok};console.log(JSON.stringify(out,null,asJson?0:2));}
main().catch(e=>{console.error(e instanceof Error?e.message:String(e));process.exit(1)});
