#!/usr/bin/env -S npx tsx
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import crypto from "node:crypto";
import { execSync } from "node:child_process";

type Check = {
  label: string;
  runtime: string;
  repo: string;
};

type Args = {
  autoPr: boolean;
  dryRun: boolean;
  repoRoot: string;
  base: string;
  branchPrefix: string;
};

function parseArgs(): Args {
  const argv = process.argv.slice(2);
  const scriptRepoRoot = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..", "..");

  let autoPr = process.env.DRIFT_AUTO_PR === "1";
  let dryRun = false;
  let repoRoot = process.env.DRIFT_REPO_ROOT || scriptRepoRoot;
  let base = process.env.DRIFT_BASE || "main";
  let branchPrefix = process.env.DRIFT_BRANCH_PREFIX || "chore/runtime-repo-drift-sync";

  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--auto-pr") autoPr = true;
    else if (arg === "--dry-run") dryRun = true;
    else if (arg === "--repo-root" && argv[i + 1]) repoRoot = argv[++i];
    else if (arg === "--base" && argv[i + 1]) base = argv[++i];
    else if (arg === "--branch-prefix" && argv[i + 1]) branchPrefix = argv[++i];
  }

  return { autoPr, dryRun, repoRoot: path.resolve(repoRoot), base, branchPrefix };
}

function digest(file: string): string | null {
  try {
    const b = fs.readFileSync(file);
    return crypto.createHash("sha256").update(b).digest("hex");
  } catch {
    return null;
  }
}

function run(cmd: string, cwd: string): string {
  return execSync(cmd, { cwd, stdio: ["ignore", "pipe", "pipe"], encoding: "utf8" }).trim();
}

function syncAndOpenPr(checks: Check[], args: Args): string {
  const drifted = checks.filter((c) => digest(c.runtime) && digest(c.repo) && digest(c.runtime) !== digest(c.repo));
  if (!drifted.length) return "";

  const stamp = new Date().toISOString().replace(/[-:TZ.]/g, "").slice(0, 12);
  const branch = `${args.branchPrefix}-${stamp}`;

  if (!args.dryRun) {
    run(`git checkout ${args.base}`, args.repoRoot);
    run(`git pull --ff-only origin ${args.base}`, args.repoRoot);
    run(`git checkout -b ${branch}`, args.repoRoot);
  }

  const copied: string[] = [];
  for (const d of drifted) {
    const rel = path.relative(args.repoRoot, d.repo);
    copied.push(rel);
    if (!args.dryRun) {
      fs.copyFileSync(d.runtime, d.repo);
      run(`git add ${JSON.stringify(rel)}`, args.repoRoot);
    }
  }

  if (args.dryRun) {
    return `DRY_RUN auto-pr: would create ${branch} with ${copied.join(", ")}`;
  }

  const hasChanges = run("git diff --cached --name-only", args.repoRoot);
  if (!hasChanges) {
    run("git checkout -", args.repoRoot);
    run(`git branch -D ${branch}`, args.repoRoot);
    return "auto-pr: no effective file changes after sync";
  }

  run(`git commit -m ${JSON.stringify("chore(cron): sync runtime drifted config to repo")}`, args.repoRoot);
  run(`git push -u origin ${branch}`, args.repoRoot);

  const title = "chore(cron): sync runtime drifted config to repo";
  const body = [
    "## Summary",
    "Automated drift sync from runtime OpenClaw config into repo backup files.",
    "",
    "## Files",
    ...copied.map((f) => `- ${f}`),
    "",
    "Generated by runtime-repo-drift-monitor.ts (--auto-pr).",
  ].join("\n");

  const prUrl = run(
    `gh pr create --base ${args.base} --head ${branch} --title ${JSON.stringify(title)} --body ${JSON.stringify(body)}`,
    args.repoRoot,
  );

  return `auto-pr opened: ${prUrl}`;
}

function main() {
  const args = parseArgs();

  const checks: Check[] = [
    {
      label: "cron/jobs.json",
      runtime: path.join(os.homedir(), ".openclaw", "cron", "jobs.json"),
      repo: path.join(args.repoRoot, "config", "cron", "jobs.json"),
    },
    {
      label: "agent-profiles.json",
      runtime: path.join(os.homedir(), ".openclaw", "agent-profiles.json"),
      repo: path.join(args.repoRoot, "config", "agent-profiles.json"),
    },
  ];

  const drift: string[] = [];
  for (const { label, runtime, repo } of checks) {
    const r = digest(runtime);
    const p = digest(repo);
    if (!r || !p) {
      drift.push(`${label}: missing file(s)`);
      continue;
    }
    if (r !== p) drift.push(`${label}: checksum mismatch`);
  }

  if (!drift.length) {
    console.log("NO_REPLY");
    return;
  }

  const lines = ["🧭 Runtime/Repo Drift Detected", ...drift.map((d) => `- ${d}`)];

  if (args.autoPr) {
    try {
      const result = syncAndOpenPr(checks, args);
      if (result) lines.push(`- ${result}`);
    } catch (error) {
      const msg = error instanceof Error ? error.message : String(error);
      lines.push(`- auto-pr failed: ${msg}`);
    }
  }

  console.log(lines.join("\n"));
}

main();
