#!/usr/bin/env npx tsx

import { runPsql, withPostgresPath } from "../lib/db.js";

const DB_NAME = process.env.DB_NAME || "cortana";

function run(sql: string, args = ["-q", "-X", "-v", "ON_ERROR_STOP=1"]): string {
  const result = runPsql(sql, {
    db: DB_NAME,
    args,
    env: withPostgresPath(process.env),
  });
  if ((result.status ?? 1) !== 0) {
    const message = String(result.stderr || result.stdout || "psql failed").trim();
    throw new Error(message || "psql failed");
  }
  return String(result.stdout || "").trim();
}

function printUsage(): void {
  console.log(`Usage: ${process.argv[1] ?? "retire-legacy-feedback.ts"} [--check|--apply]`);
}

function checkState(): void {
  const relkind = run(
    `SELECT COALESCE((SELECT c.relkind FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'public' AND c.relname = 'cortana_feedback' LIMIT 1), '');`,
    ["-t", "-A"],
  );
  const backupCount = run(
    `SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='public' AND table_name='cortana_feedback_legacy_backup';`,
    ["-t", "-A"],
  );
  const mappingCount = run(`SELECT COUNT(*) FROM mc_feedback_legacy_ids;`, ["-t", "-A"]);
  console.log(JSON.stringify({ relkind, backup_table_present: backupCount === "1", mapping_rows: Number(mappingCount || "0") }, null, 2));
}

function applyRetirement(): void {
  const sql = `
BEGIN;

CREATE TABLE IF NOT EXISTS mc_feedback_legacy_ids (
  feedback_id uuid PRIMARY KEY REFERENCES mc_feedback_items(id) ON DELETE CASCADE,
  legacy_id integer UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cortana_feedback_legacy_backup (
  id integer PRIMARY KEY,
  timestamp timestamptz,
  feedback_type varchar(50),
  context text,
  lesson text,
  applied boolean
);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relname = 'cortana_feedback' AND c.relkind = 'r'
  ) THEN
    INSERT INTO cortana_feedback_legacy_backup (id, timestamp, feedback_type, context, lesson, applied)
    SELECT cf.id, cf.timestamp, cf.feedback_type, cf.context, cf.lesson, cf.applied
    FROM cortana_feedback cf
    ON CONFLICT (id) DO NOTHING;

    WITH migrated AS (
      INSERT INTO mc_feedback_items (
        source,
        category,
        severity,
        summary,
        details,
        recurrence_key,
        status,
        remediation_status,
        created_at,
        updated_at,
        resolved_at,
        resolved_by
      )
      SELECT
        'legacy_feedback_migration',
        CASE
          WHEN lower(COALESCE(cf.feedback_type, '')) IN ('preference', 'tone') THEN 'preference'
          WHEN lower(COALESCE(cf.feedback_type, '')) IN ('approval', 'rejection', 'policy') THEN 'policy'
          ELSE 'correction'
        END,
        CASE
          WHEN lower(COALESCE(cf.feedback_type, '')) IN ('preference', 'tone', 'approval') THEN 'low'
          WHEN lower(COALESCE(cf.feedback_type, '')) IN ('guardrail_violation', 'rejection') THEN 'high'
          ELSE 'medium'
        END,
        COALESCE(cf.context, ''),
        jsonb_build_object(
          'feedback_type', COALESCE(cf.feedback_type, 'correction'),
          'context', COALESCE(cf.context, ''),
          'lesson', COALESCE(cf.lesson, ''),
          'applied', COALESCE(cf.applied, FALSE),
          'source_feedback_id', cf.id
        ),
        ('cortana_feedback:' || cf.id::text),
        CASE WHEN COALESCE(cf.applied, FALSE) THEN 'verified' ELSE 'new' END,
        CASE WHEN COALESCE(cf.applied, FALSE) THEN 'resolved' ELSE 'open' END,
        COALESCE(cf.timestamp, NOW()),
        NOW(),
        CASE WHEN COALESCE(cf.applied, FALSE) THEN COALESCE(cf.timestamp, NOW()) ELSE NULL END,
        CASE WHEN COALESCE(cf.applied, FALSE) THEN 'legacy_feedback_migration' ELSE NULL END
      FROM cortana_feedback cf
      WHERE NOT EXISTS (
        SELECT 1
        FROM mc_feedback_items m
        WHERE COALESCE(m.details->>'source_feedback_id', '') = cf.id::text
           OR (
             COALESCE(m.summary, '') = COALESCE(cf.context, '')
             AND COALESCE(m.details->>'lesson', '') = COALESCE(cf.lesson, '')
           )
      )
      RETURNING id, details->>'source_feedback_id' AS source_feedback_id
    )
    INSERT INTO mc_feedback_legacy_ids (feedback_id, legacy_id)
    SELECT m.id, (m.source_feedback_id)::integer
    FROM migrated m
    ON CONFLICT (feedback_id) DO NOTHING;

    ALTER TABLE cortana_agent_feedback DROP CONSTRAINT IF EXISTS cortana_agent_feedback_source_feedback_id_fkey;
    DROP TABLE cortana_feedback;
  END IF;
END $$;

INSERT INTO mc_feedback_legacy_ids (feedback_id)
SELECT m.id
FROM mc_feedback_items m
WHERE NOT EXISTS (
  SELECT 1 FROM mc_feedback_legacy_ids l WHERE l.feedback_id = m.id
)
ON CONFLICT (feedback_id) DO NOTHING;

CREATE OR REPLACE FUNCTION ensure_mc_feedback_legacy_id()
RETURNS trigger AS $$
BEGIN
  INSERT INTO mc_feedback_legacy_ids (feedback_id)
  VALUES (NEW.id)
  ON CONFLICT (feedback_id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS mc_feedback_legacy_id_after_insert ON mc_feedback_items;
CREATE TRIGGER mc_feedback_legacy_id_after_insert
AFTER INSERT ON mc_feedback_items
FOR EACH ROW
EXECUTE FUNCTION ensure_mc_feedback_legacy_id();

CREATE OR REPLACE VIEW cortana_feedback AS
SELECT
  l.legacy_id AS id,
  m.created_at AS timestamp,
  COALESCE(NULLIF(m.details->>'feedback_type', ''),
    CASE
      WHEN m.category = 'preference' THEN 'preference'
      WHEN m.category = 'policy' AND m.severity = 'low' THEN 'approval'
      WHEN m.category = 'policy' THEN 'rejection'
      ELSE 'correction'
    END
  )::varchar(50) AS feedback_type,
  COALESCE(m.summary, '') AS context,
  COALESCE(NULLIF(m.details->>'lesson', ''), NULLIF(m.details->>'context', ''), COALESCE(m.summary, '')) AS lesson,
  (
    COALESCE((m.details->>'applied')::boolean, FALSE)
    OR COALESCE(m.status, '') IN ('verified', 'resolved')
    OR COALESCE(m.remediation_status, '') IN ('resolved', 'wont_fix')
  ) AS applied
FROM mc_feedback_items m
JOIN mc_feedback_legacy_ids l ON l.feedback_id = m.id;

CREATE OR REPLACE FUNCTION cortana_feedback_view_insert()
RETURNS trigger AS $$
DECLARE
  created_id uuid;
  created_legacy_id integer;
BEGIN
  INSERT INTO mc_feedback_items (
    source,
    category,
    severity,
    summary,
    details,
    recurrence_key,
    status,
    remediation_status,
    created_at,
    updated_at,
    resolved_at,
    resolved_by
  )
  VALUES (
    'system',
    CASE
      WHEN lower(COALESCE(NEW.feedback_type, '')) IN ('preference', 'tone') THEN 'preference'
      WHEN lower(COALESCE(NEW.feedback_type, '')) IN ('approval', 'rejection', 'policy') THEN 'policy'
      ELSE 'correction'
    END,
    CASE
      WHEN lower(COALESCE(NEW.feedback_type, '')) IN ('preference', 'tone', 'approval') THEN 'low'
      WHEN lower(COALESCE(NEW.feedback_type, '')) IN ('guardrail_violation', 'rejection') THEN 'high'
      ELSE 'medium'
    END,
    COALESCE(NEW.context, ''),
    jsonb_build_object(
      'feedback_type', COALESCE(NEW.feedback_type, 'correction'),
      'context', COALESCE(NEW.context, ''),
      'lesson', COALESCE(NEW.lesson, ''),
      'applied', COALESCE(NEW.applied, FALSE)
    ),
    CASE WHEN COALESCE(NEW.id, 0) > 0 THEN 'cortana_feedback:' || NEW.id::text ELSE NULL END,
    CASE WHEN COALESCE(NEW.applied, FALSE) THEN 'verified' ELSE 'new' END,
    CASE WHEN COALESCE(NEW.applied, FALSE) THEN 'resolved' ELSE 'open' END,
    COALESCE(NEW.timestamp, NOW()),
    NOW(),
    CASE WHEN COALESCE(NEW.applied, FALSE) THEN COALESCE(NEW.timestamp, NOW()) ELSE NULL END,
    CASE WHEN COALESCE(NEW.applied, FALSE) THEN 'legacy_feedback_view' ELSE NULL END
  )
  RETURNING id INTO created_id;

  IF COALESCE(NEW.id, 0) > 0 THEN
    INSERT INTO mc_feedback_legacy_ids (feedback_id, legacy_id)
    VALUES (created_id, NEW.id)
    ON CONFLICT (feedback_id) DO NOTHING;
  END IF;

  SELECT legacy_id INTO created_legacy_id FROM mc_feedback_legacy_ids WHERE feedback_id = created_id;
  NEW.id := created_legacy_id;
  NEW.timestamp := COALESCE(NEW.timestamp, NOW());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS cortana_feedback_view_insert_trigger ON cortana_feedback;
CREATE TRIGGER cortana_feedback_view_insert_trigger
INSTEAD OF INSERT ON cortana_feedback
FOR EACH ROW
EXECUTE FUNCTION cortana_feedback_view_insert();

COMMIT;
`;
  run(sql, ["-q", "-X", "-v", "ON_ERROR_STOP=1"]);
}

async function main(): Promise<void> {
  const mode = process.argv[2] ?? "--check";
  if (mode === "-h" || mode === "--help") {
    printUsage();
    return;
  }
  if (mode === "--check") {
    checkState();
    return;
  }
  if (mode === "--apply") {
    applyRetirement();
    checkState();
    return;
  }
  printUsage();
  process.exit(1);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
