#!/usr/bin/env npx tsx

import { query } from "../lib/db.js";

type AnyObj = Record<string, any>;
const ACTED = new Set(["accepted","completed","in_progress","acted"]);
const DISMISSED = new Set(["dismissed","cancelled","rejected","ignored"]);
const run = (sql:string)=>query(sql).trim();
const fetchJson=(sql:string)=>JSON.parse(run(`SELECT COALESCE(json_agg(t),'[]'::json)::text FROM (${sql}) t;`)||"[]") as AnyObj[];
const exists=(name:string)=> (run(`SELECT to_regclass('${name.replace(/'/g,"''")}') IS NOT NULL;`)||"").toLowerCase()==="t";
const hasCol=(table:string,col:string)=> (run(`SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='${table}' AND column_name='${col}');`)||"").toLowerCase()==="t";
const bucket=(c:number)=> c<0.5?"0.00-0.49":c<0.65?"0.50-0.64":c<0.8?"0.65-0.79":"0.80-1.00";

function loadSignals(days:number){ let rows:AnyObj[]=[]; if(exists("cortana_proactive_signals")){ const ts=hasCol("cortana_proactive_signals","created_at")?"created_at":hasCol("cortana_proactive_signals","timestamp")?"timestamp":null; rows.push(...fetchJson(`SELECT id signal_id,COALESCE(signal_type,'unknown') signal_type,COALESCE(confidence,0)::float8 confidence,metadata FROM cortana_proactive_signals ${ts?`WHERE ${ts}>=NOW()-INTERVAL '${days} days'`:""} ORDER BY id DESC`)); }
if(rows.length<10){ rows.push(...fetchJson(`SELECT id signal_id,COALESCE(metadata->>'signal_type',metadata->>'type','unknown') signal_type,COALESCE(NULLIF(metadata->>'confidence','')::float8,0.0) confidence,metadata FROM cortana_events WHERE timestamp>=NOW()-INTERVAL '${days} days' AND (source ILIKE 'proactive%' OR event_type ILIKE 'proactive%') ORDER BY id DESC`)); }
const d=new Map<number,AnyObj>(); rows.forEach((r)=>{ const id=Number(r.signal_id||0); if(id>0&&!d.has(id)) d.set(id,r);}); return [...d.values()]; }
function loadSuggestions(days:number){ if(!exists("cortana_proactive_suggestions")) return new Map<number,AnyObj>(); const ts=hasCol("cortana_proactive_suggestions","created_at")?"created_at":hasCol("cortana_proactive_suggestions","timestamp")?"timestamp":null; const rows=fetchJson(`SELECT id,status,metadata FROM cortana_proactive_suggestions ${ts?`WHERE ${ts}>=NOW()-INTERVAL '${days} days'`:""} ORDER BY id DESC`); const out=new Map<number,AnyObj>(); rows.forEach((r)=>{ const sid=Number((r.metadata||{}).signal_id||-1); if(sid>0&&!out.has(sid)) out.set(sid,r);}); return out; }
function loadTasks(days:number){ if(!exists("cortana_tasks")) return [new Set<number>(), new Map<number,string>()] as const; const ts=hasCol("cortana_tasks","created_at")?"created_at":hasCol("cortana_tasks","timestamp")?"timestamp":null; const rows=fetchJson(`SELECT status,metadata FROM cortana_tasks WHERE ${ts?`${ts}>=NOW()-INTERVAL '${days} days' AND `:""} source='proactive-detector'`); const created=new Set<number>(); const outcomes=new Map<number,string>(); rows.forEach((r)=>{ const sid=Number((r.metadata||{}).signal_id||-1); if(sid<=0)return; created.add(sid); const st=String(r.status||"").toLowerCase(); if(st==="completed") outcomes.set(sid,"acted"); else if(["cancelled","dismissed","rejected"].includes(st)) outcomes.set(sid,"dismissed"); else if(!outcomes.has(sid)) outcomes.set(sid,"ready");}); return [created,outcomes] as const; }

async function main(){ const args=process.argv.slice(2); const days=Number(args[args.indexOf("--days")+1]||30); const target=Number(args[args.indexOf("--target-precision")+1]||0.6); const minSupport=Number(args[args.indexOf("--min-support")+1]||3); const dry=args.includes("--dry-run");
const sigs=loadSignals(days), smap=loadSuggestions(days), [created,outcomes]=loadTasks(days); const items=sigs.map((s)=>{ const sid=Number(s.signal_id||0); let state=outcomes.get(sid)||"unknown"; const sg=smap.get(sid); if(sg&&(state==="unknown"||state==="ready")){ const ss=String(sg.status||"").toLowerCase(); state=ACTED.has(ss)?"acted":DISMISSED.has(ss)?"dismissed":ss?"ready":state; } return {signal_id:sid,signal_type:String(s.signal_type||"unknown"),confidence:Number(s.confidence||0),bucket:bucket(Number(s.confidence||0)),task_created:created.has(sid),outcome:state}; }).filter((x)=>x.signal_id>0);
const grouped = new Map<string, any[]>(); items.forEach((i)=>{ const k=`${i.signal_type}|${i.bucket}`; grouped.set(k,[...(grouped.get(k)||[]),i]);});
const metrics=[...grouped.entries()].map(([k,rows])=>{ const [signal_type,confidence_bucket]=k.split("|"); const acted=rows.filter((r)=>r.outcome==="acted").length, dismissed=rows.filter((r)=>r.outcome==="dismissed").length, pending=rows.length-acted-dismissed; const denom=acted+dismissed; const precision=denom?Number((acted/denom).toFixed(3)):null; return {signal_type,confidence_bucket,support:rows.length,acted,dismissed,pending_or_unknown:pending,task_created:rows.filter((r)=>r.task_created).length,precision}; }).sort((a,b)=>a.signal_type.localeCompare(b.signal_type));
const low:any={"0.00-0.49":0,"0.50-0.64":0.5,"0.65-0.79":0.65,"0.80-1.00":0.8}; const byType=new Map<string,any[]>(); metrics.forEach((m)=>byType.set(m.signal_type,[...(byType.get(m.signal_type)||[]),m]));
const recommendations=[...byType.entries()].map(([signal_type,rows])=>{ const sorted=[...rows].sort((a,b)=>low[b.confidence_bucket]-low[a.confidence_bucket]); const chosen=sorted.find((r)=>r.support>=minSupport&&r.precision!=null&&r.precision>=target); return {signal_type,recommended_min_confidence:chosen?low[chosen.confidence_bucket]:0.8,reason:chosen?`precision ${chosen.precision.toFixed(2)} support ${chosen.support} in ${chosen.confidence_bucket}`:"insufficient high-precision evidence; tighten to 0.80"}; });
const oa=items.filter((i)=>i.outcome==="acted").length, od=items.filter((i)=>i.outcome==="dismissed").length, d=oa+od;
const summary={generated_at:new Date().toISOString(),signals_analyzed:items.length,outcomes_with_decision:d,overall_precision:d?Number((oa/d).toFixed(3)):null,metrics,recommendations};
if(!dry){ const sev=summary.overall_precision!=null&&summary.overall_precision<0.45?"warning":"info"; run(`INSERT INTO cortana_events (event_type,source,severity,message,metadata) VALUES ('proactive_calibration','evaluate_accuracy.py','${sev}','Proactive calibration complete','${JSON.stringify(summary).replace(/'/g,"''")}'::jsonb);`); }
console.log(JSON.stringify(summary,null,2)); }

main().catch((e)=>{ console.error(String(e)); process.exit(1); });
