#!/usr/bin/env npx tsx

import { spawnSync } from "child_process";
import http from "http"; import https from "https";

function httpJson(url:string, timeout=7000):Promise<any>{ return new Promise((resolve,reject)=>{ const u=new URL(url); const c=u.protocol==="https:"?https:http; const req=c.request(u,{headers:{"User-Agent":"risk-radar/1.0"}},(r)=>{ const b:Buffer[]=[]; r.on("data",(d)=>b.push(Buffer.from(d))); r.on("end",()=>{ try{ resolve(JSON.parse(Buffer.concat(b).toString("utf8"))); }catch(e){ reject(e);} });}); req.on("error",reject); req.setTimeout(timeout,()=>req.destroy(new Error("timeout"))); req.end(); }); }
const parseDt=(v?:string|null)=>{ if(!v) return null; try{ return new Date(v.endsWith("Z")?v:v); }catch{return null;} };

async function gogEvents(hours:number){ const end=new Date(Date.now()+hours*3600e3).toISOString().slice(0,10); const p=spawnSync("gog",["calendar","events","primary","--from","today","--to",end,"--json"],{encoding:"utf8"}); if(p.status!==0||!p.stdout.trim()) return []; try{ const j=JSON.parse(p.stdout); return Array.isArray(j)?j:(j.events||[]);}catch{return [];} }
async function whoop(){ for(const u of ["http://localhost:3033/whoop/recovery","http://localhost:3033/whoop/latest","http://localhost:3033/whoop","http://localhost:3033/recovery","http://localhost:3033"]) try{ const j=await httpJson(u); if(j&&typeof j==="object") return j; }catch{} return {}; }
async function alpaca(){ try{ const j=await httpJson("http://localhost:3033/alpaca/stats"); return j&&typeof j==="object"?j:{}; }catch{return {};} }
const normRecovery=(p:any):number|null=>{ for(const k of ["recovery","recovery_score","score","whoop_recovery"]) if(k in p){ const v=Number(p[k]); if(!Number.isNaN(v)) return v<=1?v*100:v; } return p.latest&&typeof p.latest==="object"?normRecovery(p.latest):null; };
const normVol=(p:any)=>{ for(const k of ["market_volatility","volatility","vix","vol_score"]) if(k in p){ const v=Number(p[k]); if(!Number.isNaN(v)) return Math.min(v,100);} if("daily_pnl_pct" in p){ const v=Math.abs(Number(p.daily_pnl_pct))*4; if(!Number.isNaN(v)) return Math.min(v,100);} return 50; };

function mitigations(r:number,c:number,v:number){ const out:string[]=[]; if(r<45&&c>55) out.push("Protect a 30–45m prep block before first high-cognitive meeting."); if(r<50&&v>60) out.push("Delay discretionary trades until after first 90 minutes of market open."); if(r<40) out.push("Set caffeine cutoff by 2pm ET and enforce early wind-down tonight."); if(c>70) out.push("Convert at least one non-critical meeting to async update."); if(v>70) out.push("Reduce order size by 25–40% and require 2:1 reward/risk minimum."); return out.length?out:["No major interventions required; keep standard risk controls."]; }

async function main(){ const args=process.argv.slice(2); const horizon=Number(args[args.indexOf("--horizon-hours")+1]||16); const who=await whoop(); let recovery=normRecovery(who); if(recovery==null) recovery=55; const ev=await gogEvents(horizon); const now=new Date(); const cutoff=new Date(Date.now()+horizon*3600e3);
const parsed=ev.map((e:any)=>{ const s=(e.start&&typeof e.start==="object")?(e.start.dateTime||e.start.date):e.start; const en=(e.end&&typeof e.end==="object")?(e.end.dateTime||e.end.date):e.end; const st=parseDt(s); const et=parseDt(en)|| (st?new Date(st.getTime()+3600e3):null); return st&&et&&st>=now&&st<=cutoff?{start:st,end:et,title:String(e.summary||"Untitled")} : null; }).filter(Boolean) as any[];
const totalM=parsed.reduce((a,e)=>a+Math.max(0,Math.floor((e.end-e.start)/60000)),0); const switchPenalty=Math.max(0,parsed.length-2)*10; const heavy=parsed.filter((e)=>/(interview|review|demo|deadline|client|presentation)/i.test(e.title)).length; const calLoad=Math.min((totalM/(horizon*60))*100+switchPenalty+heavy*6,100);
const stats=await alpaca(); const vol=normVol(stats); const combined=Math.min(0.4*(100-recovery)+0.35*calLoad+0.25*vol,100);
const windows=parsed.length?parsed.slice(0,8).map((e)=>{ const eventLoad=/(review|client|deadline|presentation)/i.test(e.title)?70:50; const score=Math.min(0.45*(100-recovery)+0.30*eventLoad+0.25*vol,100); const conf=Math.min(0.55+(recovery<50?0.15:0)+(vol>60?0.10:0),0.92); return {start:e.start.toISOString(),end:e.end.toISOString(),label:e.title,score:Number(score.toFixed(2)),confidence:Number(conf.toFixed(2)),factors:{recovery_score:recovery,event_load:eventLoad,market_volatility:vol},mitigations:mitigations(recovery,eventLoad,vol)}; }).sort((a,b)=>b.score-a.score) : [{start:now.toISOString(),end:new Date(Date.now()+Math.min(4,horizon)*3600e3).toISOString(),label:"General trading/decision window",score:Number((Math.min(0.60*(100-recovery)+0.40*vol,100)).toFixed(2)),confidence:0.64,factors:{recovery_score:recovery,calendar_load:calLoad,market_volatility:vol},mitigations:mitigations(recovery,calLoad,vol)}];
const top=windows[0]; const conf=Math.min(0.95,0.6+(Object.keys(who).length?0.15:0)+(parsed.length?0.15:0)+(Object.keys(stats).length?0.1:0));
const result={generated_at:new Date().toISOString(),horizon_hours:horizon,inputs:{whoop_available:!!Object.keys(who).length,calendar_events:parsed.length,alpaca_stats_available:!!Object.keys(stats).length},scores:{recovery_score:Number(recovery.toFixed(2)),calendar_load_score:Number(calLoad.toFixed(2)),market_volatility_score:Number(vol.toFixed(2)),combined_risk_score:Number(combined.toFixed(2)),confidence:Number(conf.toFixed(2))},risk_windows:windows,high_risk_detected:!!(top&&top.score>=65),priority_mitigations:top?top.mitigations.slice(0,3):[],morning_brief:{headline:combined>=65?"High-friction day: protect decision quality windows.":"Risk posture stable: execute plan with normal controls.",one_liner:`Recovery ${recovery.toFixed(0)}, Calendar load ${calLoad.toFixed(0)}, Volatility ${vol.toFixed(0)}.`}};
console.log(JSON.stringify(result,null,2)); }

main().catch((e)=>{ console.error(String(e)); process.exit(1); });
